CREATE TABLE parametros (
	parametro VARCHAR2(30) NOT NULL,
	valor VARCHAR2(255) NOT NULL,
	detalle VARCHAR2(255) NOT NULL,
	tipo VARCHAR2(3) NOT NULL,	
	CONSTRAINT PARAMETROS_PK PRIMARY KEY (parametro)
);